package com.example.azurlaneguide

object HMSEquipmentImage : HMSEquipmentActivity() {

    // TODO: Update images with equipment images

    // Destroyers
    const val acasta = "https://i.imgur.com/OMDWGTm.png"
    const val amazon = "https://i.imgur.com/GZxh8C3.png"
    const val ardent = "https://i.imgur.com/t37CHOm.png"
    const val beagle = "https://i.imgur.com/ADADko6.png"
    const val bulldog = "https://i.imgur.com/Px737wo.png"
    const val comet = "https://i.imgur.com/ObNSsmP.png"
    const val crescent = "https://i.imgur.com/Mpthstm.png"
    const val cygnet = "https://i.imgur.com/TawIno9.png"
    const val echo = "https://i.imgur.com/0kxxebb.png"
    const val fortune = "https://i.imgur.com/huvUJVn.png"
    const val foxhound = "https://i.imgur.com/lNlddVO.png"
    const val glowworm = "https://i.imgur.com/3kM4mrQ.png"
    const val grenville = "https://i.imgur.com/SBfLPtp.png"
    const val hardy = "https://i.imgur.com/qr6mhfs.png"
    const val hunter = "https://i.imgur.com/113hz9j.png"
    const val javelin = "https://i.imgur.com/rz6Hw2B.png"
    const val jersey = "https://i.imgur.com/c4jrBrn.png"
    const val juno = "https://i.imgur.com/0Gqs5ow.png"
    const val jupiter = "https://i.imgur.com/tGleRvV.png"
    const val matchless = "https://i.imgur.com/tiQx8PV.png"
    const val musketeer = "https://i.imgur.com/CkkHuVU.png"
    const val vampire = "https://i.imgur.com/e153els.png"

    // Light Cruisers
    const val achilles = "https://i.imgur.com/5ygqws9.png"
    const val ajax = "https://i.imgur.com/7BU6jzs.png"
    const val arethusa = "https://i.imgur.com/y6rzZE3.png"
    const val aurora = "https://i.imgur.com/pwE9Fu6.png"
    const val belfast = "https://i.imgur.com/qC7wt4U.png"
    const val blackPrince = "https://i.imgur.com/TWgyxRm.png"
    const val curacoa = "https://i.imgur.com/aZaaBVV.png"
    const val curlew = "https://i.imgur.com/MzbbLYn.png"
    const val edinburgh = "https://i.imgur.com/aDHxecW.png"
    const val fiji = "https://i.imgur.com/jrViHbA.png"
    const val galatea = "https://i.imgur.com/8i5qBPy.png"
    const val neptune = "https://i.imgur.com/MLULV9V.png"
    const val jamaica = "https://i.imgur.com/fR0h7NE.png"
    const val leander = "https://i.imgur.com/I28Advg.png"
    const val littleBel = "https://i.imgur.com/ApJ0oGN.png"
    const val newcastle = "https://i.imgur.com/1KArGSg.png"
    const val sheffield = "https://i.imgur.com/PcHx09E.png"
    const val sirius = "https://i.imgur.com/1yEgAuZ.png"
    const val southampton = "https://i.imgur.com/jSL0aYo.png"
    const val swiftsure = "https://i.imgur.com/sx3Vu9x.png"

    // Heavy Cruisers
    const val dorsetshire = "https://i.imgur.com/Gxirt7L.png"
    const val exeter = "https://i.imgur.com/e9apVj8.png"
    const val kent = "https://i.imgur.com/Z96z7i2.png"
    const val london = "https://i.imgur.com/MLNaonZ.png"
    const val norfolk = "https://i.imgur.com/8NkK8eo.png"
    const val shirosphire = "https://i.imgur.com/sLt6HHb.png"
    const val suffolk = "https://i.imgur.com/LNMDcpJ.png"
    const val sussex = "https://i.imgur.com/xukq40y.png"
    const val york = "https://i.imgur.com/B2BcRXa.png"

    // Battleships
    const val abercrombie = "https://i.imgur.com/GtIV0oF.png"
    const val dukeOfYork = "https://i.imgur.com/GizdIVk.png"
    const val erebus = "https://i.imgur.com/NrPrZnE.png"
    const val hood = "https://i.imgur.com/6XZL6Q7.png"
    const val kingGeorgeV = "https://i.imgur.com/0UcPvB4.png"
    const val monarch = "https://i.imgur.com/1rk97qv.png"
    const val nelson = "https://i.imgur.com/K7KmgbS.png"
    const val princeOfWales = "https://i.imgur.com/PT0leCm.png"
    const val queenElizabeth = "https://i.imgur.com/VE9s7wB.png"
    const val renown = "https://i.imgur.com/vmZrarj.png"
    const val repulse = "https://i.imgur.com/7MYyTiB.png"
    const val rodney = "https://i.imgur.com/XAI7upx.png"
    const val terror = "https://i.imgur.com/AeTHMSE.png"
    const val warspite = "https://i.imgur.com/DNUCGei.png"

    //Aircraft Carriers
    const val arkRoyal = "https://i.imgur.com/DzwREFH.png"
    const val centaur = "https://i.imgur.com/qVipQi8.png"
    const val chaser = "https://i.imgur.com/KFgWJzq.png"
    const val formidable = "https://i.imgur.com/Meos3EL.png"
    const val glorious = "https://i.imgur.com/xtoN3FV.png"
    const val hermes = "https://i.imgur.com/AvpMwan.png"
    const val illustrious = "https://i.imgur.com/8NMUPvq.png"
    const val unicorn = "https://i.imgur.com/O19NRdb.png"
    const val victorious = "https://i.imgur.com/twPOhim.png"
}