package com.example.azurlaneguide

object HMSEquipmentImage : HMSEquipmentActivity() {

    // Destroyers
    const val acasta = "https://i.imgur.com/NdbLZsU.png"
    const val amazon = "https://i.imgur.com/NdbLZsU.png"
    const val ardent = "https://i.imgur.com/NdbLZsU.png"
    const val beagle = "https://i.imgur.com/NdbLZsU.png"
    const val bulldog = "https://i.imgur.com/NdbLZsU.png"
    const val comet = "https://i.imgur.com/NdbLZsU.png"
    const val crescent = "https://i.imgur.com/NdbLZsU.png"
    const val cygnet = "https://i.imgur.com/NdbLZsU.png"
    const val echo = "https://i.imgur.com/NdbLZsU.png"
    const val fortune = "https://i.imgur.com/NdbLZsU.png"
    const val foxhound = "https://i.imgur.com/NdbLZsU.png"
    const val glowworm = "https://i.imgur.com/NdbLZsU.png"
    const val grenville = "https://i.imgur.com/NdbLZsU.png"
    const val hardy = "https://i.imgur.com/NdbLZsU.png"
    const val hunter = "https://i.imgur.com/NdbLZsU.png"
    const val javelin = "https://i.imgur.com/ShpkPAb.png"
    const val jersey = "https://i.imgur.com/NdbLZsU.png"
    const val juno = "https://i.imgur.com/NdbLZsU.png"
    const val jupiter = "https://i.imgur.com/NdbLZsU.png"
    const val matchless = "https://i.imgur.com/NdbLZsU.png"
    const val musketeer = "https://i.imgur.com/NdbLZsU.png"
    const val vampire = "https://i.imgur.com/NdbLZsU.png"

    // Light Cruisers
    const val achilles = "https://i.imgur.com/w8T9JT2.png"
    const val ajax = "https://i.imgur.com/w8T9JT2.png"
    const val arethusa = "https://i.imgur.com/w8T9JT2.png"
    const val aurora = "https://i.imgur.com/w8T9JT2.png"
    const val belfast = "https://i.imgur.com/MVr2r7x.png"
    const val blackPrince = "https://i.imgur.com/w8T9JT2.png"
    const val curacoa = "https://i.imgur.com/paHM1NG.png"
    const val curlew = "https://i.imgur.com/paHM1NG.png"
    const val dido = "https://i.imgur.com/SZmo64B.png"
    const val edinburgh = "https://i.imgur.com/w8T9JT2.png"
    const val fiji = "https://i.imgur.com/w8T9JT2.png"
    const val galatea = "https://i.imgur.com/w8T9JT2.png"
    const val glasgow = "https://i.imgur.com/w8T9JT2.png"
    const val gloucester = "https://i.imgur.com/w8T9JT2.png"
    const val neptune = "https://i.imgur.com/w8T9JT2.png"
    const val jamaica = "https://i.imgur.com/w8T9JT2.png"
    const val leander = "https://i.imgur.com/w8T9JT2.png"
    const val littleBel = "https://i.imgur.com/w8T9JT2.png"
    const val newcastle = "https://i.imgur.com/w8T9JT2.png"
    const val sheffield = "https://i.imgur.com/w8T9JT2.png"
    const val sirius = "https://i.imgur.com/Y9DqYYv.png"
    const val southampton = "https://i.imgur.com/koKsQXU.png"
    const val swiftsure = "https://i.imgur.com/w8T9JT2.png"

    // Heavy Cruisers
    const val dorsetshire = "https://i.imgur.com/vC2mrVG.png"
    const val exeter = "https://i.imgur.com/vC2mrVG.png"
    const val kent = "https://i.imgur.com/vC2mrVG.png"
    const val london = "https://i.imgur.com/4t29N3h.png"
    const val norfolk = "https://i.imgur.com/vC2mrVG.png"
    const val shirosphire = "https://i.imgur.com/f8QV3uj.png"
    const val suffolk = "https://i.imgur.com/f8QV3uj.png"
    const val sussex = "https://i.imgur.com/f8QV3uj.png"
    const val york = "https://i.imgur.com/vC2mrVG.png"

    // Battleships
    const val abercrombie = "https://i.imgur.com/rHYquvs.png"
    const val dukeOfYork = "https://i.imgur.com/kYTO4F2.png"
    const val erebus = "https://i.imgur.com/rHYquvs.png"
    const val hood = "https://i.imgur.com/uieFOJg.png"
    const val kingGeorgeV = "https://i.imgur.com/0R0Q8mB.png"
    const val monarch = "https://i.imgur.com/z2D28CS.png"
    const val nelson = "https://i.imgur.com/4TBHDeH.png"
    const val princeOfWales = "https://i.imgur.com/kYTO4F2.png"
    const val queenElizabeth = "https://i.imgur.com/kYTO4F2.png"
    const val renown = "https://i.imgur.com/4TBHDeH.png"
    const val repulse = "https://i.imgur.com/4TBHDeH.png"
    const val rodney = "https://i.imgur.com/kYTO4F2.png"
    const val terror = "https://i.imgur.com/rHYquvs.png"
    const val warspite = "https://i.imgur.com/kYTO4F2.png"

    //Aircraft Carriers
    const val arkRoyal = "https://i.imgur.com/IMdCjvK.png"
    const val centaur = "https://i.imgur.com/yACBeks.png"
    const val chaser = "https://i.imgur.com/U93SOMt.png"
    const val formidable = "https://i.imgur.com/9EIKDdu.png"
    const val glorious = "https://i.imgur.com/n4qWPrr.png"
    const val hermes = "https://i.imgur.com/3IgplAZ.png"
    const val illustrious = "https://i.imgur.com/Mp32dKA.png"
    const val unicorn = "https://i.imgur.com/U93SOMt.png"
    const val victorious = "https://i.imgur.com/20lr32T.png"
}