package com.example.azurlaneguide

object IJNEquipmentImage : IJNEquipmentActivity() {

    // TODO: Update images with equipment images

    // Destroyers
    const val akatsuki = "https://i.imgur.com/UcFmQOM.png"
    const val arashio = "https://i.imgur.com/1hgEBER.png"
    const val ariake = "https://i.imgur.com/WZR3ZDQ.png"
    const val asashio = "https://i.imgur.com/kZsgKV7.png"
    const val ayanami = "https://i.imgur.com/y9IHovK.png"
    const val fubuki = "https://i.imgur.com/GYuEsoA.png"
    const val fumizuki = "https://i.imgur.com/prUntIK.png"
    const val hamakaze = "https://i.imgur.com/p9VpT3o.png"
    const val harutsuki = "https://i.imgur.com/Mqa4ztF.png"
    const val hatakaze = "https://i.imgur.com/huvUJVn.png"
    const val hatsuharu = "https://i.imgur.com/lNlddVO.png"
    const val hatsushimo = "https://i.imgur.com/d1MhZcK.png"
    const val ikazuchi = "https://i.imgur.com/SBfLPtp.png"
    const val inazuma = "https://i.imgur.com/qr6mhfs.png"
    const val isokaze = "https://i.imgur.com/113hz9j.png"
    const val kagerou = "https://i.imgur.com/rz6Hw2B.png"
    const val kamikaze = "https://i.imgur.com/c4jrBrn.png"
    const val kawakaze = "https://i.imgur.com/0Gqs5ow.png"
    const val kisaragi = "https://i.imgur.com/tGleRvV.png"
    const val kitakaze = "https://i.imgur.com/tiQx8PV.png"
    const val kiyonami = "https://i.imgur.com/CkkHuVU.png"
    const val kuroshio = "https://i.imgur.com/TcVlhMi.png"
    const val makinami = "https://i.imgur.com/jEYJl9I.png"
    const val matsukaze = "https://i.imgur.com/VnqPrsE.png"
    const val michishio = "https://i.imgur.com/97kCFBD.png"
    const val mikazuki = "https://i.imgur.com/AgQdDrN.png"
    const val minazuki = "https://i.imgur.com/9m8TPj8.png"
    const val mutsuki = "https://i.imgur.com/YzAlcl0.png"
    const val nagatsuki = "https://i.imgur.com/KfQon6k.png"
    const val niizuki = "https://i.imgur.com/DtAzpON.png"
    const val nowaki = "https://i.imgur.com/ZsDdOgM.png"
    const val ooshio = "https://i.imgur.com/9lXXKBr.png"
    const val oyashio = "https://i.imgur.com/8C8ul4O.png"
    const val shigure = "https://i.imgur.com/X1JVKfN.png"
    const val shiranui = "https://i.imgur.com/VJnUN0r.png"
    const val shiratsuyu = "https://i.imgur.com/PJTcRlF.png"
    const val tanikaze = "https://i.imgur.com/oWoIAch.png"
    const val urakaze = "https://i.imgur.com/JHUgjNF.png"
    const val uzuki = "https://i.imgur.com/fgO1FjE.png"
    const val wakaba = "https://i.imgur.com/EXvRJW3.png"
    const val yoizuki = "https://i.imgur.com/8mTUVF1.png"
    const val yukikaze = "https://i.imgur.com/ZvoOEvq.png"
    const val yuudachi = "https://i.imgur.com/0xyOjwl.png"
    const val yuugure = "https://i.imgur.com/OJcYCpt.png"

    // Light Cruisers
    const val abukuma = "https://i.imgur.com/gM8T10D.png"
    const val agano = "https://i.imgur.com/zK1weP8.png"
    const val isuzu = "https://i.imgur.com/PaSIQpP.png"
    const val jintsuu = "https://i.imgur.com/xZgGgof.png"
    const val mikuma = "https://i.imgur.com/Sn0GeSu.png"
    const val mogami = "https://i.imgur.com/7EnWCXl.png"
    const val nagara = ""
    const val naka = ""
    const val sendai = ""
    const val yuubari = ""

    // Heavy Cruisers
    const val aoba = ""
    const val ashigara = ""
    const val atago = ""
    const val choukai = ""
    const val furutaka = ""
    const val ibuki = ""
    const val kako = ""
    const val kinugasa = ""
    const val maya = ""
    const val myoukou = ""
    const val nachi = ""
    const val suzuya = ""
    const val takao = ""

    // Battleships
    const val amagi = ""
    const val azuma = ""
    const val fusou = ""
    const val haruna = ""
    const val hiei = ""
    const val hieiChan = ""
    const val hyuuga = ""
    const val ise = ""
    const val izumo = ""
    const val kaga = ""
    const val kirishima = ""
    const val kongou = ""
    const val mikasa = ""
    const val mutsu = ""
    const val nagato = ""
    const val yamashiro = ""

    //Aircraft Carriers
    const val akagi = ""
    const val akagiChan = ""
    const val akashi = ""
    const val hiryuu = ""
    const val hiyou = ""
    const val houshou = ""
    const val junyou = ""
    const val kagaB = ""
    const val ryuujou = ""
    const val shouhou = ""
    const val shoukaku = ""
    const val souryuu = ""
    const val taihou = ""
    const val zuikaku = ""

    //Submarines
    const val i13 = ""
    const val i19 = ""
    const val i25 = ""
    const val i26 = ""
    const val i56 = ""
    const val i58 = ""
    const val i168 = ""
}