package com.example.azurlaneguide

object USSEquipmentImage : USSEquipmentActivity() {

    // TODO: Update images with equipment images

    // Destroyers
    const val aulick = "https://i.imgur.com/iuIzC0z.png"
    const val aylwin = "https://i.imgur.com/1RY3mi8.png"
    const val bache = "https://i.imgur.com/ABO6wLS.png"
    const val bailey = "https://i.imgur.com/pX6onI5.png"
    const val benson = "https://i.imgur.com/cx6bhr3.png"
    const val bush = "https://i.imgur.com/euGmHSJ.png"
    const val cassin = "https://i.imgur.com/0e2yCAI.png"
    const val charles_ausburne = "https://i.imgur.com/IzbzGvr.png"
    const val craven = "https://i.imgur.com/RGx7hTW.png"
    const val dewey = "https://i.imgur.com/MusODlc.png"
    const val downes = "https://i.imgur.com/gcyIPRc.png"
    const val eldridge = "https://i.imgur.com/oJ42quk.png"
    const val fletcher = "https://i.imgur.com/mxIKyPR.png"
    const val foote = "https://i.imgur.com/MnrmsmP.png"
    const val gridley = "https://i.imgur.com/KMivyCq.png"
    const val hammann = "https://i.imgur.com/AuHI9AU.png"
    const val hazelwood = "https://i.imgur.com/8x7NgqA.png"
    const val hobby = "https://i.imgur.com/uT7XtZN.png"
    const val jenkins = "https://i.imgur.com/olqZrEF.png"
    const val kalk = "https://i.imgur.com/NxQvRSl.png"
    const val kimberly = "https://i.imgur.com/ifrxsd6.png"
    const val laffey = "https://i.imgur.com/CFxqShJ.png"
    const val maury = "https://i.imgur.com/dFuy8mc.png"
    const val mccall = "https://i.imgur.com/Mr5A8Kn.png"
    const val mullany = "https://i.imgur.com/zegMeFg.png"
    const val nicholas = "https://i.imgur.com/GRF5D2e.png"
    const val radford = "https://i.imgur.com/J03VJPW.png"
    const val sims = "https://i.imgur.com/dc3GmCL.png"
    const val spence = "https://i.imgur.com/9xlJ4Ft.png"
    const val stanley = "https://i.imgur.com/T5Cv116.png"
    const val thatcher = "https://i.imgur.com/YoA5PWE.png"

    // Light Cruisers
    const val atlanta = "https://i.imgur.com/cCVD4Bs.png"
    const val birmmingham = "https://i.imgur.com/gFRTuma.png"
    const val brooklyn = "https://i.imgur.com/r3MGQL0.png"
    const val clevelad = "https://i.imgur.com/Gy86eCu.png"
    const val cleveland = "https://i.imgur.com/Thua47P.png"
    const val columbia = "https://i.imgur.com/FGH4LYe.png"
    const val concord = "https://i.imgur.com/F7SsRUB.png"
    const val denver = "https://i.imgur.com/k48E1rs.png"
    const val helena = "https://i.imgur.com/xcvK95N.png"
    const val honolulu = "https://i.imgur.com/U1HAkOE.png"
    const val juneau = "https://i.imgur.com/qfwgEcd.png"
    const val lena = "https://i.imgur.com/nuvWQrW.png"
    const val lil_sandy = "https://i.imgur.com/VcIWMPA.png"
    const val memphis = "https://i.imgur.com/D9G175k.png"
    const val montpelier = "https://i.imgur.com/UJkZU1K.png"
    const val omaha = "https://i.imgur.com/K8CbeyR.png"
    const val phoenix = "https://i.imgur.com/xhda3Sh.png"
    const val raleigh = "https://i.imgur.com/zLd1qZa.png"
    const val richmond = "https://i.imgur.com/8aHxKjE.png"
    const val san_diego = "https://i.imgur.com/8aHxKjE.png"
    const val san_juan = "https://i.imgur.com/8aHxKjE.png"
    const val seattle = "https://i.imgur.com/8aHxKjE.png"
    const val st_louis = "https://i.imgur.com/8aHxKjE.png"

    // Heavy Cruisers
    const val astoria = "https://i.imgur.com/mwmUYs9.png"
    const val baltimore = "https://i.imgur.com/mwmUYs9.png"
    const val chicago = "https://i.imgur.com/mwmUYs9.png"
    const val houston = "https://i.imgur.com/mwmUYs9.png"
    const val indianapolis = "https://i.imgur.com/mwmUYs9.png"
    const val minneapolis = "https://i.imgur.com/mwmUYs9.png"
    const val northampton = "https://i.imgur.com/mwmUYs9.png"
    const val pensacola = "https://i.imgur.com/mwmUYs9.png"
    const val portland = "https://i.imgur.com/mwmUYs9.png"
    const val quincy = "https://i.imgur.com/mwmUYs9.png"
    const val salt_lake_city = "https://i.imgur.com/mwmUYs9.png"
    const val vincennes = "https://i.imgur.com/mwmUYs9.png"
    const val wichita = "https://i.imgur.com/mwmUYs9.png"

    // Battleships
    const val alabama = "https://i.imgur.com/v4H0R1Z.png"
    const val arizona = "https://i.imgur.com/v4H0R1Z.png"
    const val california = "https://i.imgur.com/v4H0R1Z.png"
    const val colorado = "https://i.imgur.com/v4H0R1Z.png"
    const val georgia = "https://i.imgur.com/v4H0R1Z.png"
    const val maryland = "https://i.imgur.com/v4H0R1Z.png"
    const val massachusetts = "https://i.imgur.com/v4H0R1Z.png"
    const val north_carolina = "https://i.imgur.com/v4H0R1Z.png"
    const val oklahoma = "https://i.imgur.com/v4H0R1Z.png"
    const val pennsylvania = "https://i.imgur.com/v4H0R1Z.png"
    const val south_dakota = "https://i.imgur.com/v4H0R1Z.png"
    const val tennessee = "https://i.imgur.com/v4H0R1Z.png"
    const val washington = "https://i.imgur.com/v4H0R1Z.png"
    const val west_virginia = "https://i.imgur.com/v4H0R1Z.png"
    const val nevada = "https://i.imgur.com/v4H0R1Z.png"

    //Aircraft Carriers
    const val bataan = "https://i.imgur.com/fwmVvpa.png"
    const val bogue = "https://i.imgur.com/fwmVvpa.png"
    const val bunker_hill = "https://i.imgur.com/fwmVvpa.png"
    const val enterprise = "https://i.imgur.com/fwmVvpa.png"
    const val essex = "https://i.imgur.com/fwmVvpa.png"
    const val hornet = "https://i.imgur.com/fwmVvpa.png"
    const val independence = "https://i.imgur.com/fwmVvpa.png"
    const val langley = "https://i.imgur.com/fwmVvpa.png"
    const val lexington = "https://i.imgur.com/fwmVvpa.png"
    const val long_island = "https://i.imgur.com/fwmVvpa.png"
    const val ranger = "https://i.imgur.com/fwmVvpa.png"
    const val saratoga = "https://i.imgur.com/fwmVvpa.png"
    const val shanri_la = "https://i.imgur.com/fwmVvpa.png"
    const val vestal = "https://i.imgur.com/fwmVvpa.png"
    const val wasp = "https://i.imgur.com/fwmVvpa.png"
    const val yorktown = "https://i.imgur.com/fwmVvpa.png"

    // Submarines
    const val albacore = "https://i.imgur.com/v6OG54l.png"
    const val cavalla = "https://i.imgur.com/v6OG54l.png"
    const val dace = "https://i.imgur.com/v6OG54l.png"
}