package com.example.azurlaneguide

object USSEquipmentImage : USSEquipmentActivity() {
//TODO: halseyPowell,biloxi
    // Destroyers
    const val aulick = "https://i.imgur.com/NdbLZsU.png"
    const val aylwin = "https://i.imgur.com/NdbLZsU.png"
    const val bache = "https://i.imgur.com/NdbLZsU.png"
    const val bailey = "https://i.imgur.com/NdbLZsU.png"
    const val benson = "https://i.imgur.com/NdbLZsU.png"
    const val bush = "https://i.imgur.com/NdbLZsU.png"
    const val cassin = "https://i.imgur.com/NdbLZsU.png"
    const val charles_ausburne = "https://i.imgur.com/NdbLZsU.png"
    const val craven = "https://i.imgur.com/NdbLZsU.png"
    const val dewey = "https://i.imgur.com/NdbLZsU.png"
    const val downes = "https://i.imgur.com/NdbLZsU.png"
    const val eldridge = "https://i.imgur.com/ShpkPAb.png"
    const val fletcher = "https://i.imgur.com/NdbLZsU.png"
    const val foote = "https://i.imgur.com/NdbLZsU.png"
    const val gridley = "https://i.imgur.com/NdbLZsU.png"
    const val halseyPowell = "https://i.imgur.com/KMivyCq.png"
    const val hammann = "https://i.imgur.com/NdbLZsU.png"
    const val hazelwood = "https://i.imgur.com/NdbLZsU.png"
    const val hobby = "https://i.imgur.com/NdbLZsU.png"
    const val jenkins = "https://i.imgur.com/NdbLZsU.png"
    const val kalk = "https://i.imgur.com/NdbLZsU.png"
    const val kimberly = "https://i.imgur.com/NdbLZsU.png"
    const val laffey = "https://i.imgur.com/Yrmt1cX.png"
    const val maury = "https://i.imgur.com/NdbLZsU.png"
    const val mccall = "https://i.imgur.com/NdbLZsU.png"
    const val mullany = "https://i.imgur.com/NdbLZsU.png"
    const val nicholas = "https://i.imgur.com/NdbLZsU.png"
    const val radford = "https://i.imgur.com/NdbLZsU.png"
    const val sims = "https://i.imgur.com/NdbLZsU.png"
    const val spence = "https://i.imgur.com/NdbLZsU.png"
    const val stanley = "https://i.imgur.com/NdbLZsU.png"
    const val thatcher = "https://i.imgur.com/NdbLZsU.png"

    // Light Cruisers
    const val atlanta = "https://i.imgur.com/SZmo64B.png"
    const val biloxi = "https://i.imgur.com/SZmo64B.png"
    const val birmmingham = "https://i.imgur.com/koKsQXU.png"
    const val brooklyn = "https://i.imgur.com/koKsQXU.png"
    const val clevelad = "https://i.imgur.com/koKsQXU.png"
    const val cleveland = "https://i.imgur.com/koKsQXU.png"
    const val columbia = "https://i.imgur.com/koKsQXU.png"
    const val concord = "https://i.imgur.com/koKsQXU.png"
    const val denver = "https://i.imgur.com/koKsQXU.png"
    const val helena = "https://i.imgur.com/koKsQXU.png"
    const val honolulu = "https://i.imgur.com/koKsQXU.png"
    const val juneau = "https://i.imgur.com/SZmo64B.png"
    const val lena = "https://i.imgur.com/koKsQXU.png"
    const val lil_sandy = "https://i.imgur.com/w8T9JT2.png"
    const val memphis = "https://i.imgur.com/w8T9JT2.png"
    const val montpelier = "https://i.imgur.com/koKsQXU.png"
    const val omaha = "https://i.imgur.com/koKsQXU.png"
    const val phoenix = "https://i.imgur.com/koKsQXU.png"
    const val raleigh = "https://i.imgur.com/koKsQXU.png"
    const val richmond = "https://i.imgur.com/koKsQXU.png"
    const val san_diego = "https://i.imgur.com/SZmo64B.png"
    const val san_juan = "https://i.imgur.com/SZmo64B.png"
    const val seattle = "https://i.imgur.com/0bBKox5.png"
    const val st_louis = "https://i.imgur.com/koKsQXU.png"

    // Heavy Cruisers
    const val astoria = "https://i.imgur.com/b1USe0z.png"
    const val baltimore = "https://i.imgur.com/qEDoAtX.png"
    const val chicago = "https://i.imgur.com/V4Haum1.png"
    const val houston = "https://i.imgur.com/b1USe0z.png"
    const val indianapolis = "https://i.imgur.com/b1USe0z.png"
    const val minneapolis = "https://i.imgur.com/b1USe0z.png"
    const val northampton = "https://i.imgur.com/vC2mrVG.png"
    const val pensacola = "https://i.imgur.com/b1USe0z.png"
    const val portland = "https://i.imgur.com/b1USe0z.png"
    const val quincy = "https://i.imgur.com/b1USe0z.png"
    const val salt_lake_city = "https://i.imgur.com/b1USe0z.png"
    const val vincennes = "https://i.imgur.com/b1USe0z.png"
    const val wichita = "https://i.imgur.com/V4Haum1.png"

    // Battleships
    const val alabama = "https://i.imgur.com/4TBHDeH.png"
    const val arizona = "https://i.imgur.com/sHQ2moG.png"
    const val california = "https://i.imgur.com/4TBHDeH.png"
    const val colorado = "https://i.imgur.com/4TBHDeH.png"
    const val georgia = "https://i.imgur.com/fwkwolp.png"
    const val maryland = "https://i.imgur.com/4TBHDeH.png"
    const val massachusetts = "https://i.imgur.com/ZbwlNwK.png"
    const val north_carolina = "https://i.imgur.com/4TBHDeH.png"
    const val oklahoma = "https://i.imgur.com/4TBHDeH.png"
    const val pennsylvania = "https://i.imgur.com/4TBHDeH.png"
    const val south_dakota = "https://i.imgur.com/4TBHDeH.png"
    const val tennessee = "https://i.imgur.com/4TBHDeH.png"
    const val washington = "https://i.imgur.com/4TBHDeH.png"
    const val west_virginia = "https://i.imgur.com/4TBHDeH.png"
    const val nevada = "https://i.imgur.com/4TBHDeH.png"

    //Aircraft Carriers
    const val bataan = "https://i.imgur.com/ndN77YB.png"
    const val bogue = "https://i.imgur.com/zp1PJmM.png"
    const val bunker_hill = "https://i.imgur.com/20lr32T.png"
    const val enterprise = "https://i.imgur.com/20lr32T.png"
    const val essex = "https://i.imgur.com/20lr32T.png"
    const val hornet = "https://i.imgur.com/20lr32T.png"
    const val independence = "https://i.imgur.com/U93SOMt.png"
    const val langley = "https://i.imgur.com/TzN60md.png"
    const val lexington = "https://i.imgur.com/ZfNQXYB.png"
    const val long_island = "https://i.imgur.com/zp1PJmM.png"
    const val ranger = "https://i.imgur.com/ChXGgN5.png"
    const val saratoga = "https://i.imgur.com/ZfNQXYB.png"
    const val shanri_la = "https://i.imgur.com/20lr32T.png"
    const val vestal = "https://i.imgur.com/tRDa3R3.png"
    const val wasp = "https://i.imgur.com/20lr32T.png"
    const val yorktown = "https://i.imgur.com/20lr32T.png"

    // Submarines
    const val albacore = "https://i.imgur.com/FVCm1Fi.png"
    const val cavalla = "https://i.imgur.com/FVCm1Fi.png"
    const val dace = "https://i.imgur.com/FVCm1Fi.png"
}