package com.al.equipmentguide

object IJNEquipmentImage : IJNEquipmentActivity() {

    // Destroyers
    const val akatsuki = "https://i.imgur.com/NdbLZsU.png"
    const val arashio = "https://i.imgur.com/NdbLZsU.png"
    const val ariake = "https://i.imgur.com/NdbLZsU.png"
    const val asashio = "https://i.imgur.com/NdbLZsU.png"
    const val ayanami = "https://i.imgur.com/f4DOm5O.png"
    const val fubuki = "https://i.imgur.com/NdbLZsU.png"
    const val fumizuki = "https://i.imgur.com/NdbLZsU.png"
    const val hamakaze = "https://i.imgur.com/NdbLZsU.png"
    const val harutsuki = "https://i.imgur.com/NdbLZsU.png"
    const val hatakaze = "https://i.imgur.com/NdbLZsU.png"
    const val hatsuharu = "https://i.imgur.com/NdbLZsU.png"
    const val hatsushimo = "https://i.imgur.com/NdbLZsU.png"
    const val hibiki = "https://i.imgur.com/NdbLZsU.png"
    const val ikazuchi = "https://i.imgur.com/NdbLZsU.png"
    const val inazuma = "https://i.imgur.com/NdbLZsU.png"
    const val isokaze = "https://i.imgur.com/NdbLZsU.png"
    const val kagerou = "https://i.imgur.com/NdbLZsU.png"
    const val kamikaze = "https://i.imgur.com/NdbLZsU.png"
    const val kasumi = "https://i.imgur.com/NdbLZsU.png"
    const val kawakaze = "https://i.imgur.com/f4DOm5O.png"
    const val kisaragi = "https://i.imgur.com/NdbLZsU.png"
    const val kitakaze = "https://i.imgur.com/7SMcJMl.png"
    const val kiyonami = "https://i.imgur.com/NdbLZsU.png"
    const val kuroshio = "https://i.imgur.com/NdbLZsU.png"
    const val makinami = "https://i.imgur.com/NdbLZsU.png"
    const val matsukaze = "https://i.imgur.com/NdbLZsU.png"
    const val michishio = "https://i.imgur.com/NdbLZsU.png"
    const val mikazuki = "https://i.imgur.com/NdbLZsU.png"
    const val minazuki = "https://i.imgur.com/NdbLZsU.png"
    const val mutsuki = "https://i.imgur.com/NdbLZsU.png"
    const val nagatsuki = "https://i.imgur.com/NdbLZsU.png"
    const val niizuki = "https://i.imgur.com/NdbLZsU.png"
    const val nowaki = "https://i.imgur.com/NdbLZsU.png"
    const val ooshio = "https://i.imgur.com/NdbLZsU.png"
    const val oyashio = "https://i.imgur.com/NdbLZsU.png"
    const val shigure = "https://i.imgur.com/NdbLZsU.png"
    const val shiranui = "https://i.imgur.com/NdbLZsU.png"
    const val shiratsuyu = "https://i.imgur.com/NdbLZsU.png"
    const val tanikaze = "https://i.imgur.com/NdbLZsU.png"
    const val urakaze = "https://i.imgur.com/NdbLZsU.png"
    const val uranami = "https://i.imgur.com/NdbLZsU.png"
    const val uzuki = "https://i.imgur.com/NdbLZsU.png"
    const val wakaba = "https://i.imgur.com/NdbLZsU.png"
    const val yoizuki = "https://i.imgur.com/NdbLZsU.png"
    const val yukikaze = "https://i.imgur.com/f4DOm5O.png"
    const val yuudachi = "https://i.imgur.com/f4DOm5O.png"
    const val yuugure = "https://i.imgur.com/NdbLZsU.png"

    // Light Cruisers
    const val abukuma = "https://i.imgur.com/w8T9JT2.png"
    const val agano = "https://i.imgur.com/LnjlKiG.png"
    const val isuzu = "https://i.imgur.com/SZmo64B.png"
    const val jintsuu = "https://i.imgur.com/LnjlKiG.png"
    const val kinu = "https://i.imgur.com/w8T9JT2.png"
    const val mikuma = "https://i.imgur.com/w8T9JT2.png"
    const val mogami = "https://i.imgur.com/w8T9JT2.png" // CA and CL
    const val nagara = "https://i.imgur.com/w8T9JT2.png"
    const val naka = "https://i.imgur.com/w8T9JT2.png"
    const val noshiro = "https://i.imgur.com/LnjlKiG.png"
    const val sendai = "https://i.imgur.com/LnjlKiG.png"
    const val yuubari = "https://i.imgur.com/w8T9JT2.png"

    // Heavy Cruisers
    const val aoba = "https://i.imgur.com/vC2mrVG.png"
    const val ashigara = "https://i.imgur.com/vC2mrVG.png"
    const val atago = "https://i.imgur.com/xy0RQek.png"
    const val choukai = "https://i.imgur.com/f8QV3uj.png"
    const val furutaka = "https://i.imgur.com/vC2mrVG.png"
    const val ibuki = "https://i.imgur.com/Qn8uofH.png"
    const val kako = "https://i.imgur.com/vC2mrVG.png"
    const val kinugasa = "https://i.imgur.com/vC2mrVG.png"
    const val maya = "https://i.imgur.com/vC2mrVG.png"
    const val myoukou = "https://i.imgur.com/vC2mrVG.png"
    const val nachi = "https://i.imgur.com/vC2mrVG.png"
    const val suzuya = "https://i.imgur.com/vC2mrVG.png"
    const val takao = "https://i.imgur.com/f8QV3uj.png"

    // Battleships
    const val amagi = "https://i.imgur.com/sWH4HoO.png"
    const val azuma = "https://i.imgur.com/8THxtLW.png"
    const val fusou = "https://i.imgur.com/5NS1zAE.png" // 2 pic
    const val haruna = "https://i.imgur.com/kYTO4F2.png"
    const val hiei = "https://i.imgur.com/4TBHDeH.png"
    const val hieiChan = "https://i.imgur.com/kYTO4F2.png"
    const val hyuuga = "https://i.imgur.com/5NS1zAE.png" // 2 pic
    const val ise = "https://i.imgur.com/5NS1zAE.png" // 2 pic
    const val izumo = "https://i.imgur.com/kYTO4F2.png"
    const val kagaB = "https://i.imgur.com/kYTO4F2.png"
    const val kirishima = "https://i.imgur.com/sWH4HoO.png"
    const val kongou = "https://i.imgur.com/kYTO4F2.png"
    const val mikasa = "https://i.imgur.com/4TBHDeH.png"
    const val mutsu = "https://i.imgur.com/kYTO4F2.png"
    const val nagato = "https://i.imgur.com/z2D28CS.png"
    const val suruga = "https://i.imgur.com/4TBHDeH.png"
    const val yamashiro = "https://i.imgur.com/5NS1zAE.png" // 2 pic

    //Aircraft Carriers
    const val akagi = "https://i.imgur.com/20lr32T.png"
    const val akagiChan = "https://i.imgur.com/20lr32T.png"
    const val akagiMuse = "https://i.imgur.com/20lr32T.png"
    const val akashi = "https://i.imgur.com/HuZbfsv.png"
    const val hiryuu = "https://i.imgur.com/20lr32T.png"
    const val hiyou = "https://i.imgur.com/yoNiInt.png"
    const val houshou = "https://i.imgur.com/aLKRpWb.png"
    const val junyou = "https://i.imgur.com/yoNiInt.png"
    const val kaga = "https://i.imgur.com/20lr32T.png"
    const val ryuuhou = "https://i.imgur.com/U93SOMt.png"
    const val ryuujou = "https://i.imgur.com/U93SOMt.png"
    const val shouhou = "https://i.imgur.com/zp1PJmM.png"
    const val shoukaku = "https://i.imgur.com/20lr32T.png"
    const val souryuu = "https://i.imgur.com/20lr32T.png"
    const val taihou = "https://i.imgur.com/20lr32T.png"
    const val zuikaku = "https://i.imgur.com/20lr32T.png"

    //Submarines
    const val i13 = "https://i.imgur.com/FVCm1Fi.png"
    const val i19 = "https://i.imgur.com/FVCm1Fi.png"
    const val i25 = "https://i.imgur.com/FVCm1Fi.png"
    const val i26 = "https://i.imgur.com/FVCm1Fi.png"
    const val i56 = "https://i.imgur.com/FVCm1Fi.png"
    const val i58 = "https://i.imgur.com/FVCm1Fi.png"
    const val i168 = "https://i.imgur.com/FVCm1Fi.png"
}